### ISSUE TITLE
Frame skip might not be required (already handled in ALE)

### ISSUE THREAD

**Issue by d6y** [d9w/CGP.jl#12]
In the Atari experiment there's a probablistic action repeat (frame skip?):

https://github.com/d9w/CGP.jl/blob/d82cc4b48c9c957a971bddea8f8da916824f231f/experiments/atari.jl#L23-L25

My reading of this is that the behaviour (or something very similar) is enabled by default in ALE (since 0.5):

> When you call self.ale.act(a) for some action a, the action a will be executed right away
with a probability (1 - p), otherwise, the action that was previously
executed will be executed again. The default value for p right now is 0.25.

^^ from: https://github.com/mgbellemare/Arcade-Learning-Environment/issues/166#issuecomment-260140061

I assume it's safe to remove this test from the code (unless there's an ale.cfg in place to disable the default ALE behaviour). 

Apologies in advance if I've mised the point :-/ ...still learning.

**Comment by d9w** [comment]
I did use an ale.cfg to set this parameter to 0 and implemented frameskip
myself. This was to allow for deterministic behavior based on the random
seed.

Le lun. 29 oct. 2018 à 11:53, Richard Dallaway <notifications@github.com> a
écrit :

**Comment by d6y** [comment]
Great! Thanks for clarifying that.
