### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by ghost** [d9w/CGP.jl#5]
Some kind of evolution algorithm:
https://github.com/S6Regen/Thunderbird
There is a paper on the internet "Continuous Gray code optimization" that describes the algorithm used.

**Comment by d9w** [comment]
Alright, I'll take a look at that. I'm closing this as an issue though, because it isn't clear how this is relevant to CGP.jl. If you have an improvement to suggest or bug in CGP.jl, feel free to open it as an issue.
