### ISSUE TITLE
UndefVarError: Game not defined

### ISSUE THREAD

**Issue by d6y** [d9w/CGP.jl#8]
Hello - thank you for sharing this project: very cool!

This issue is almost certainly my problem, but pointers would be appreciated.

I've worked through the examples in the readme (xor, etc) and they all work great. For the Atari experiments I'm hitting:

```
$ julia experiments/atari.jl
WARNING: Method definition info(Any...) in module Base at util.jl:534 overwritten in module Logging at ~/julia/v0.6/Logging/src/Logging.jl:115.
WARNING: Method definition warn(Any...) in module Base at util.jl:589 overwritten in module Logging at ~/.julia/v0.6/Logging/src/Logging.jl:115.
ERROR: LoadError: UndefVarError: Game not defined
Stacktrace:
 [1] get_params(::Dict{String,Any}) at CGP.jl/experiments/atari.jl:71
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] process_options(::Base.JLOptions) at ./client.jl:305
 [5] _start() at ./client.jl:371
```
I'm on MacOS, I have Julia 0.6.4 installed, and I've run:

```
Pkg.add("ArcadeLearningEnvironment")
```
I assume I'm missing another step.

**Comment by d9w** [comment]
Hi, sorry this isn't in the README, but please checkout my fork of ArcadeLearningEnvironment.jl, where I provide the Game class:

Pkg.checkout("https://github.com/d9w/ArcadeLearningEnvironment.jl")

**Comment by d9w** [comment]
Reopening for visibility

**Comment by mostafagwely2** [comment]
when i try this `Pkg.checkout("https://github.com/d9w/ArcadeLearningEnvironment.jl")`
gives me 
`ERROR: https://github.com/d9w/ArcadeLearningEnvironment.jl isn't a git repo `

**Comment by d9w** [comment]
Now `scripts/atari_ram.jl` depends on https://github.com/JuliaReinforcementLearning/ArcadeLearningEnvironment.jl
